package handlers

import (
	"encoding/json"
	"net/http"
)

type ApproveMergeRequest struct {
	SuggestionID string `json:"suggestion_id"`
}

type RejectMergeRequest struct {
	SuggestionID string `json:"suggestion_id"`
}

func (h *AppHandler) ListMergeSuggestions(w http.ResponseWriter, r *http.Request) {
	// Returns pending merge suggestions generated by LLM Stage 2 adjudication
	RenderJSON(w, http.StatusOK, map[string]interface{}{
		"status": "success",
		"suggestions": []map[string]interface{}{
			{
				"id":               "sug_01",
				"confidence_score": 0.94,
				"reasoning":        "Cùng email (hoang.nguyen@vinai.io), tên viết tắt tương đồng (Nguyễn Văn Hoàng vs N. V. Hoàng), cùng sự kiện AI Summit 2025.",
				"canonical_entity": map[string]string{
					"display_name":         "Nguyễn Văn Hoàng",
					"primary_organization": "VinAI Research",
					"primary_email":        "hoang.nguyen@vinai.io",
					"primary_role":         "Chuyên gia AI Cấp cao",
				},
				"candidate_record": map[string]string{
					"full_name":    "N. V. Hoàng",
					"organization": "VinAI",
					"email":        "hoang.nguyen@vinai.io",
					"role_title":   "Senior AI Scientist",
					"event_name":   "Diễn đàn Trí tuệ Nhân tạo 2025",
					"event_date":   "10/08/2025",
				},
			},
			{
				"id":               "sug_02",
				"confidence_score": 0.88,
				"reasoning":        "Tên công ty trùng khớp (Tập đoàn FPT), số điện thoại giống 100%, tên cá nhân biến thể gõ dấu (Phạm Quốc Bảo vs Pham Quoc Bao).",
				"canonical_entity": map[string]string{
					"display_name":         "Phạm Quốc Bảo",
					"primary_organization": "Tập đoàn FPT",
					"primary_email":        "bao.pq@fpt.com.vn",
					"primary_role":         "Trưởng phòng Đầu tư",
				},
				"candidate_record": map[string]string{
					"full_name":    "Pham Quoc Bao",
					"organization": "FPT Corp",
					"email":        "bao.pq@fpt.com.vn",
					"role_title":   "Investment Manager",
					"event_name":   "Ngày hội Khởi nghiệp Sang tạo 2025",
					"event_date":   "25/08/2025",
				},
			},
		},
	})
}

func (h *AppHandler) ApproveMerge(w http.ResponseWriter, r *http.Request) {
	var req ApproveMergeRequest
	_ = json.NewDecoder(r.Body).Decode(&req)

	RenderJSON(w, http.StatusOK, map[string]interface{}{
		"status":        "success",
		"message":       "Đã phê duyệt hợp nhất thực thể thành công",
		"suggestion_id": req.SuggestionID,
	})
}

func (h *AppHandler) RejectMerge(w http.ResponseWriter, r *http.Request) {
	var req RejectMergeRequest
	_ = json.NewDecoder(r.Body).Decode(&req)

	RenderJSON(w, http.StatusOK, map[string]interface{}{
		"status":        "success",
		"message":       "Đã từ chối gợi ý hợp nhất. Bản ghi âm tính sẽ được ghi nhớ.",
		"suggestion_id": req.SuggestionID,
	})
}
